import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "@/provider/theme-provider";
import type { Metadata } from "next";
import { Figtree, Geist_Mono, Nunito, Urbanist } from "next/font/google";
import "./globals.css";

const urbanistSans = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});
const nunitoSans = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});
const figtreeSans = Figtree({
  variable: "--font-figtree-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${urbanistSans.variable} ${geistMono.variable} ${figtreeSans.variable} ${nunitoSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
